// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ozoncp/ocp-solution-api/internal/repo (interfaces: Repo)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/ozoncp/ocp-solution-api/internal/models"
)

// MockRepo is a mock of Repo interface.
type MockRepo struct {
	ctrl     *gomock.Controller
	recorder *MockRepoMockRecorder
}

// MockRepoMockRecorder is the mock recorder for MockRepo.
type MockRepoMockRecorder struct {
	mock *MockRepo
}

// NewMockRepo creates a new mock instance.
func NewMockRepo(ctrl *gomock.Controller) *MockRepo {
	mock := &MockRepo{ctrl: ctrl}
	mock.recorder = &MockRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepo) EXPECT() *MockRepoMockRecorder {
	return m.recorder
}

// AddSolutions mocks base method.
func (m *MockRepo) AddSolutions(arg0 []models.Solution) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddSolutions", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddSolutions indicates an expected call of AddSolutions.
func (mr *MockRepoMockRecorder) AddSolutions(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddSolutions", reflect.TypeOf((*MockRepo)(nil).AddSolutions), arg0)
}
