// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: api/ocp-verdict-api/ocp-verdict-api.proto

package ocp_verdict_api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Verdict_Status int32

const (
	Verdict_InProgress       Verdict_Status = 0
	Verdict_Passed           Verdict_Status = 1
	Verdict_Failed           Verdict_Status = 2
	Verdict_SyntaxError      Verdict_Status = 3
	Verdict_CompilationError Verdict_Status = 4
	Verdict_Dropped          Verdict_Status = 5
)

// Enum value maps for Verdict_Status.
var (
	Verdict_Status_name = map[int32]string{
		0: "InProgress",
		1: "Passed",
		2: "Failed",
		3: "SyntaxError",
		4: "CompilationError",
		5: "Dropped",
	}
	Verdict_Status_value = map[string]int32{
		"InProgress":       0,
		"Passed":           1,
		"Failed":           2,
		"SyntaxError":      3,
		"CompilationError": 4,
		"Dropped":          5,
	}
)

func (x Verdict_Status) Enum() *Verdict_Status {
	p := new(Verdict_Status)
	*p = x
	return p
}

func (x Verdict_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Verdict_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_api_ocp_verdict_api_ocp_verdict_api_proto_enumTypes[0].Descriptor()
}

func (Verdict_Status) Type() protoreflect.EnumType {
	return &file_api_ocp_verdict_api_ocp_verdict_api_proto_enumTypes[0]
}

func (x Verdict_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Verdict_Status.Descriptor instead.
func (Verdict_Status) EnumDescriptor() ([]byte, []int) {
	return file_api_ocp_verdict_api_ocp_verdict_api_proto_rawDescGZIP(), []int{8, 0}
}

type CreateVerdictV1Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VerdictId uint64 `protobuf:"varint,1,opt,name=VerdictId,proto3" json:"VerdictId,omitempty"`
	IssueId   uint64 `protobuf:"varint,2,opt,name=issueId,proto3" json:"issueId,omitempty"`
}

func (x *CreateVerdictV1Request) Reset() {
	*x = CreateVerdictV1Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_verdict_api_ocp_verdict_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateVerdictV1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVerdictV1Request) ProtoMessage() {}

func (x *CreateVerdictV1Request) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_verdict_api_ocp_verdict_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVerdictV1Request.ProtoReflect.Descriptor instead.
func (*CreateVerdictV1Request) Descriptor() ([]byte, []int) {
	return file_api_ocp_verdict_api_ocp_verdict_api_proto_rawDescGZIP(), []int{0}
}

func (x *CreateVerdictV1Request) GetVerdictId() uint64 {
	if x != nil {
		return x.VerdictId
	}
	return 0
}

func (x *CreateVerdictV1Request) GetIssueId() uint64 {
	if x != nil {
		return x.IssueId
	}
	return 0
}

type CreateVerdictV1Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Verdict *Verdict `protobuf:"bytes,1,opt,name=Verdict,proto3" json:"Verdict,omitempty"`
}

func (x *CreateVerdictV1Response) Reset() {
	*x = CreateVerdictV1Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_verdict_api_ocp_verdict_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateVerdictV1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVerdictV1Response) ProtoMessage() {}

func (x *CreateVerdictV1Response) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_verdict_api_ocp_verdict_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVerdictV1Response.ProtoReflect.Descriptor instead.
func (*CreateVerdictV1Response) Descriptor() ([]byte, []int) {
	return file_api_ocp_verdict_api_ocp_verdict_api_proto_rawDescGZIP(), []int{1}
}

func (x *CreateVerdictV1Response) GetVerdict() *Verdict {
	if x != nil {
		return x.Verdict
	}
	return nil
}

type ListVerdictsV1Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Limit  uint64 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset uint64 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
}

func (x *ListVerdictsV1Request) Reset() {
	*x = ListVerdictsV1Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_verdict_api_ocp_verdict_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListVerdictsV1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVerdictsV1Request) ProtoMessage() {}

func (x *ListVerdictsV1Request) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_verdict_api_ocp_verdict_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVerdictsV1Request.ProtoReflect.Descriptor instead.
func (*ListVerdictsV1Request) Descriptor() ([]byte, []int) {
	return file_api_ocp_verdict_api_ocp_verdict_api_proto_rawDescGZIP(), []int{2}
}

func (x *ListVerdictsV1Request) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListVerdictsV1Request) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListVerdictsV1Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Verdicts []*Verdict `protobuf:"bytes,1,rep,name=Verdicts,proto3" json:"Verdicts,omitempty"`
}

func (x *ListVerdictsV1Response) Reset() {
	*x = ListVerdictsV1Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_verdict_api_ocp_verdict_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListVerdictsV1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVerdictsV1Response) ProtoMessage() {}

func (x *ListVerdictsV1Response) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_verdict_api_ocp_verdict_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVerdictsV1Response.ProtoReflect.Descriptor instead.
func (*ListVerdictsV1Response) Descriptor() ([]byte, []int) {
	return file_api_ocp_verdict_api_ocp_verdict_api_proto_rawDescGZIP(), []int{3}
}

func (x *ListVerdictsV1Response) GetVerdicts() []*Verdict {
	if x != nil {
		return x.Verdicts
	}
	return nil
}

type DescribeVerdictV1Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VerdictId uint64 `protobuf:"varint,1,opt,name=VerdictId,proto3" json:"VerdictId,omitempty"`
}

func (x *DescribeVerdictV1Request) Reset() {
	*x = DescribeVerdictV1Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_verdict_api_ocp_verdict_api_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DescribeVerdictV1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeVerdictV1Request) ProtoMessage() {}

func (x *DescribeVerdictV1Request) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_verdict_api_ocp_verdict_api_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeVerdictV1Request.ProtoReflect.Descriptor instead.
func (*DescribeVerdictV1Request) Descriptor() ([]byte, []int) {
	return file_api_ocp_verdict_api_ocp_verdict_api_proto_rawDescGZIP(), []int{4}
}

func (x *DescribeVerdictV1Request) GetVerdictId() uint64 {
	if x != nil {
		return x.VerdictId
	}
	return 0
}

type DescribeVerdictV1Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Verdict *Verdict `protobuf:"bytes,1,opt,name=Verdict,proto3" json:"Verdict,omitempty"`
}

func (x *DescribeVerdictV1Response) Reset() {
	*x = DescribeVerdictV1Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_verdict_api_ocp_verdict_api_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DescribeVerdictV1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeVerdictV1Response) ProtoMessage() {}

func (x *DescribeVerdictV1Response) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_verdict_api_ocp_verdict_api_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeVerdictV1Response.ProtoReflect.Descriptor instead.
func (*DescribeVerdictV1Response) Descriptor() ([]byte, []int) {
	return file_api_ocp_verdict_api_ocp_verdict_api_proto_rawDescGZIP(), []int{5}
}

func (x *DescribeVerdictV1Response) GetVerdict() *Verdict {
	if x != nil {
		return x.Verdict
	}
	return nil
}

type RemoveVerdictV1Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VerdictId uint64 `protobuf:"varint,1,opt,name=VerdictId,proto3" json:"VerdictId,omitempty"`
}

func (x *RemoveVerdictV1Request) Reset() {
	*x = RemoveVerdictV1Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_verdict_api_ocp_verdict_api_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveVerdictV1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveVerdictV1Request) ProtoMessage() {}

func (x *RemoveVerdictV1Request) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_verdict_api_ocp_verdict_api_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveVerdictV1Request.ProtoReflect.Descriptor instead.
func (*RemoveVerdictV1Request) Descriptor() ([]byte, []int) {
	return file_api_ocp_verdict_api_ocp_verdict_api_proto_rawDescGZIP(), []int{6}
}

func (x *RemoveVerdictV1Request) GetVerdictId() uint64 {
	if x != nil {
		return x.VerdictId
	}
	return 0
}

type RemoveVerdictV1Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Found bool `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
}

func (x *RemoveVerdictV1Response) Reset() {
	*x = RemoveVerdictV1Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_verdict_api_ocp_verdict_api_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveVerdictV1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveVerdictV1Response) ProtoMessage() {}

func (x *RemoveVerdictV1Response) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_verdict_api_ocp_verdict_api_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveVerdictV1Response.ProtoReflect.Descriptor instead.
func (*RemoveVerdictV1Response) Descriptor() ([]byte, []int) {
	return file_api_ocp_verdict_api_ocp_verdict_api_proto_rawDescGZIP(), []int{7}
}

func (x *RemoveVerdictV1Response) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type Verdict struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SolutionId uint64         `protobuf:"varint,1,opt,name=solutionId,proto3" json:"solutionId,omitempty"`
	UserId     uint64         `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Status     Verdict_Status `protobuf:"varint,3,opt,name=status,proto3,enum=ocp.verdict.api.Verdict_Status" json:"status,omitempty"`
	Timestamp  int64          `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Comment    string         `protobuf:"bytes,5,opt,name=comment,proto3" json:"comment,omitempty"`
}

func (x *Verdict) Reset() {
	*x = Verdict{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_verdict_api_ocp_verdict_api_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Verdict) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Verdict) ProtoMessage() {}

func (x *Verdict) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_verdict_api_ocp_verdict_api_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Verdict.ProtoReflect.Descriptor instead.
func (*Verdict) Descriptor() ([]byte, []int) {
	return file_api_ocp_verdict_api_ocp_verdict_api_proto_rawDescGZIP(), []int{8}
}

func (x *Verdict) GetSolutionId() uint64 {
	if x != nil {
		return x.SolutionId
	}
	return 0
}

func (x *Verdict) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Verdict) GetStatus() Verdict_Status {
	if x != nil {
		return x.Status
	}
	return Verdict_InProgress
}

func (x *Verdict) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Verdict) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

var File_api_ocp_verdict_api_ocp_verdict_api_proto protoreflect.FileDescriptor

var file_api_ocp_verdict_api_ocp_verdict_api_proto_rawDesc = []byte{
	0x0a, 0x29, 0x61, 0x70, 0x69, 0x2f, 0x6f, 0x63, 0x70, 0x2d, 0x76, 0x65, 0x72, 0x64, 0x69, 0x63,
	0x74, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x6f, 0x63, 0x70, 0x2d, 0x76, 0x65, 0x72, 0x64, 0x69, 0x63,
	0x74, 0x2d, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x6f, 0x63, 0x70,
	0x2e, 0x76, 0x65, 0x72, 0x64, 0x69, 0x63, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x22, 0x50, 0x0a, 0x16,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x56, 0x65, 0x72, 0x64, 0x69, 0x63, 0x74, 0x56, 0x31, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x56, 0x65, 0x72, 0x64, 0x69, 0x63,
	0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x56, 0x65, 0x72, 0x64, 0x69,
	0x63, 0x74, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x73, 0x73, 0x75, 0x65, 0x49, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x69, 0x73, 0x73, 0x75, 0x65, 0x49, 0x64, 0x22, 0x4d,
	0x0a, 0x17, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x56, 0x65, 0x72, 0x64, 0x69, 0x63, 0x74, 0x56,
	0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x07, 0x56, 0x65, 0x72,
	0x64, 0x69, 0x63, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6f, 0x63, 0x70,
	0x2e, 0x76, 0x65, 0x72, 0x64, 0x69, 0x63, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x56, 0x65, 0x72,
	0x64, 0x69, 0x63, 0x74, 0x52, 0x07, 0x56, 0x65, 0x72, 0x64, 0x69, 0x63, 0x74, 0x22, 0x45, 0x0a,
	0x15, 0x4c, 0x69, 0x73, 0x74, 0x56, 0x65, 0x72, 0x64, 0x69, 0x63, 0x74, 0x73, 0x56, 0x31, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x6f, 0x66,
	0x66, 0x73, 0x65, 0x74, 0x22, 0x4e, 0x0a, 0x16, 0x4c, 0x69, 0x73, 0x74, 0x56, 0x65, 0x72, 0x64,
	0x69, 0x63, 0x74, 0x73, 0x56, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x34,
	0x0a, 0x08, 0x56, 0x65, 0x72, 0x64, 0x69, 0x63, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x18, 0x2e, 0x6f, 0x63, 0x70, 0x2e, 0x76, 0x65, 0x72, 0x64, 0x69, 0x63, 0x74, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x56, 0x65, 0x72, 0x64, 0x69, 0x63, 0x74, 0x52, 0x08, 0x56, 0x65, 0x72, 0x64,
	0x69, 0x63, 0x74, 0x73, 0x22, 0x38, 0x0a, 0x18, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65,
	0x56, 0x65, 0x72, 0x64, 0x69, 0x63, 0x74, 0x56, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1c, 0x0a, 0x09, 0x56, 0x65, 0x72, 0x64, 0x69, 0x63, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x09, 0x56, 0x65, 0x72, 0x64, 0x69, 0x63, 0x74, 0x49, 0x64, 0x22, 0x4f,
	0x0a, 0x19, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x56, 0x65, 0x72, 0x64, 0x69, 0x63,
	0x74, 0x56, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x07, 0x56,
	0x65, 0x72, 0x64, 0x69, 0x63, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6f,
	0x63, 0x70, 0x2e, 0x76, 0x65, 0x72, 0x64, 0x69, 0x63, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x56,
	0x65, 0x72, 0x64, 0x69, 0x63, 0x74, 0x52, 0x07, 0x56, 0x65, 0x72, 0x64, 0x69, 0x63, 0x74, 0x22,
	0x36, 0x0a, 0x16, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x56, 0x65, 0x72, 0x64, 0x69, 0x63, 0x74,
	0x56, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x56, 0x65, 0x72,
	0x64, 0x69, 0x63, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x56, 0x65,
	0x72, 0x64, 0x69, 0x63, 0x74, 0x49, 0x64, 0x22, 0x2f, 0x0a, 0x17, 0x52, 0x65, 0x6d, 0x6f, 0x76,
	0x65, 0x56, 0x65, 0x72, 0x64, 0x69, 0x63, 0x74, 0x56, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x05, 0x66, 0x6f, 0x75, 0x6e, 0x64, 0x22, 0x98, 0x02, 0x0a, 0x07, 0x56, 0x65, 0x72,
	0x64, 0x69, 0x63, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x73, 0x6f, 0x6c, 0x75, 0x74, 0x69,
	0x6f, 0x6e, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x37, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1f, 0x2e, 0x6f,
	0x63, 0x70, 0x2e, 0x76, 0x65, 0x72, 0x64, 0x69, 0x63, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x56,
	0x65, 0x72, 0x64, 0x69, 0x63, 0x74, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x64, 0x0a,
	0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0e, 0x0a, 0x0a, 0x49, 0x6e, 0x50, 0x72, 0x6f,
	0x67, 0x72, 0x65, 0x73, 0x73, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x50, 0x61, 0x73, 0x73, 0x65,
	0x64, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x46, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x10, 0x02, 0x12,
	0x0f, 0x0a, 0x0b, 0x53, 0x79, 0x6e, 0x74, 0x61, 0x78, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x10, 0x03,
	0x12, 0x14, 0x0a, 0x10, 0x43, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x10, 0x04, 0x12, 0x0b, 0x0a, 0x07, 0x44, 0x72, 0x6f, 0x70, 0x70, 0x65,
	0x64, 0x10, 0x05, 0x32, 0xb2, 0x03, 0x0a, 0x0d, 0x4f, 0x63, 0x70, 0x56, 0x65, 0x72, 0x64, 0x69,
	0x63, 0x74, 0x41, 0x70, 0x69, 0x12, 0x66, 0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x56,
	0x65, 0x72, 0x64, 0x69, 0x63, 0x74, 0x56, 0x31, 0x12, 0x27, 0x2e, 0x6f, 0x63, 0x70, 0x2e, 0x76,
	0x65, 0x72, 0x64, 0x69, 0x63, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x56, 0x65, 0x72, 0x64, 0x69, 0x63, 0x74, 0x56, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x28, 0x2e, 0x6f, 0x63, 0x70, 0x2e, 0x76, 0x65, 0x72, 0x64, 0x69, 0x63, 0x74, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x56, 0x65, 0x72, 0x64, 0x69, 0x63,
	0x74, 0x56, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x63, 0x0a,
	0x0e, 0x4c, 0x69, 0x73, 0x74, 0x56, 0x65, 0x72, 0x64, 0x69, 0x63, 0x74, 0x73, 0x56, 0x31, 0x12,
	0x26, 0x2e, 0x6f, 0x63, 0x70, 0x2e, 0x76, 0x65, 0x72, 0x64, 0x69, 0x63, 0x74, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x56, 0x65, 0x72, 0x64, 0x69, 0x63, 0x74, 0x73, 0x56, 0x31,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x6f, 0x63, 0x70, 0x2e, 0x76, 0x65,
	0x72, 0x64, 0x69, 0x63, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x56, 0x65,
	0x72, 0x64, 0x69, 0x63, 0x74, 0x73, 0x56, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x6c, 0x0a, 0x11, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x56, 0x65,
	0x72, 0x64, 0x69, 0x63, 0x74, 0x56, 0x31, 0x12, 0x29, 0x2e, 0x6f, 0x63, 0x70, 0x2e, 0x76, 0x65,
	0x72, 0x64, 0x69, 0x63, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x62, 0x65, 0x56, 0x65, 0x72, 0x64, 0x69, 0x63, 0x74, 0x56, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x2a, 0x2e, 0x6f, 0x63, 0x70, 0x2e, 0x76, 0x65, 0x72, 0x64, 0x69, 0x63, 0x74,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x56, 0x65, 0x72,
	0x64, 0x69, 0x63, 0x74, 0x56, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x66, 0x0a, 0x0f, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x56, 0x65, 0x72, 0x64, 0x69, 0x63,
	0x74, 0x56, 0x31, 0x12, 0x27, 0x2e, 0x6f, 0x63, 0x70, 0x2e, 0x76, 0x65, 0x72, 0x64, 0x69, 0x63,
	0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x56, 0x65, 0x72, 0x64,
	0x69, 0x63, 0x74, 0x56, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e, 0x6f,
	0x63, 0x70, 0x2e, 0x76, 0x65, 0x72, 0x64, 0x69, 0x63, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x52,
	0x65, 0x6d, 0x6f, 0x76, 0x65, 0x56, 0x65, 0x72, 0x64, 0x69, 0x63, 0x74, 0x56, 0x31, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x48, 0x5a, 0x46, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x7a, 0x6f, 0x6e, 0x63, 0x70, 0x2f, 0x6f, 0x63,
	0x70, 0x2d, 0x73, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x70,
	0x6b, 0x67, 0x2f, 0x6f, 0x63, 0x70, 0x2d, 0x76, 0x65, 0x72, 0x64, 0x69, 0x63, 0x74, 0x2d, 0x61,
	0x70, 0x69, 0x3b, 0x6f, 0x63, 0x70, 0x5f, 0x76, 0x65, 0x72, 0x64, 0x69, 0x63, 0x74, 0x5f, 0x61,
	0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_ocp_verdict_api_ocp_verdict_api_proto_rawDescOnce sync.Once
	file_api_ocp_verdict_api_ocp_verdict_api_proto_rawDescData = file_api_ocp_verdict_api_ocp_verdict_api_proto_rawDesc
)

func file_api_ocp_verdict_api_ocp_verdict_api_proto_rawDescGZIP() []byte {
	file_api_ocp_verdict_api_ocp_verdict_api_proto_rawDescOnce.Do(func() {
		file_api_ocp_verdict_api_ocp_verdict_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_ocp_verdict_api_ocp_verdict_api_proto_rawDescData)
	})
	return file_api_ocp_verdict_api_ocp_verdict_api_proto_rawDescData
}

var file_api_ocp_verdict_api_ocp_verdict_api_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_ocp_verdict_api_ocp_verdict_api_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_api_ocp_verdict_api_ocp_verdict_api_proto_goTypes = []interface{}{
	(Verdict_Status)(0),               // 0: ocp.verdict.api.Verdict.Status
	(*CreateVerdictV1Request)(nil),    // 1: ocp.verdict.api.CreateVerdictV1Request
	(*CreateVerdictV1Response)(nil),   // 2: ocp.verdict.api.CreateVerdictV1Response
	(*ListVerdictsV1Request)(nil),     // 3: ocp.verdict.api.ListVerdictsV1Request
	(*ListVerdictsV1Response)(nil),    // 4: ocp.verdict.api.ListVerdictsV1Response
	(*DescribeVerdictV1Request)(nil),  // 5: ocp.verdict.api.DescribeVerdictV1Request
	(*DescribeVerdictV1Response)(nil), // 6: ocp.verdict.api.DescribeVerdictV1Response
	(*RemoveVerdictV1Request)(nil),    // 7: ocp.verdict.api.RemoveVerdictV1Request
	(*RemoveVerdictV1Response)(nil),   // 8: ocp.verdict.api.RemoveVerdictV1Response
	(*Verdict)(nil),                   // 9: ocp.verdict.api.Verdict
}
var file_api_ocp_verdict_api_ocp_verdict_api_proto_depIdxs = []int32{
	9, // 0: ocp.verdict.api.CreateVerdictV1Response.Verdict:type_name -> ocp.verdict.api.Verdict
	9, // 1: ocp.verdict.api.ListVerdictsV1Response.Verdicts:type_name -> ocp.verdict.api.Verdict
	9, // 2: ocp.verdict.api.DescribeVerdictV1Response.Verdict:type_name -> ocp.verdict.api.Verdict
	0, // 3: ocp.verdict.api.Verdict.status:type_name -> ocp.verdict.api.Verdict.Status
	1, // 4: ocp.verdict.api.OcpVerdictApi.CreateVerdictV1:input_type -> ocp.verdict.api.CreateVerdictV1Request
	3, // 5: ocp.verdict.api.OcpVerdictApi.ListVerdictsV1:input_type -> ocp.verdict.api.ListVerdictsV1Request
	5, // 6: ocp.verdict.api.OcpVerdictApi.DescribeVerdictV1:input_type -> ocp.verdict.api.DescribeVerdictV1Request
	7, // 7: ocp.verdict.api.OcpVerdictApi.RemoveVerdictV1:input_type -> ocp.verdict.api.RemoveVerdictV1Request
	2, // 8: ocp.verdict.api.OcpVerdictApi.CreateVerdictV1:output_type -> ocp.verdict.api.CreateVerdictV1Response
	4, // 9: ocp.verdict.api.OcpVerdictApi.ListVerdictsV1:output_type -> ocp.verdict.api.ListVerdictsV1Response
	6, // 10: ocp.verdict.api.OcpVerdictApi.DescribeVerdictV1:output_type -> ocp.verdict.api.DescribeVerdictV1Response
	8, // 11: ocp.verdict.api.OcpVerdictApi.RemoveVerdictV1:output_type -> ocp.verdict.api.RemoveVerdictV1Response
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_ocp_verdict_api_ocp_verdict_api_proto_init() }
func file_api_ocp_verdict_api_ocp_verdict_api_proto_init() {
	if File_api_ocp_verdict_api_ocp_verdict_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_ocp_verdict_api_ocp_verdict_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateVerdictV1Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_verdict_api_ocp_verdict_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateVerdictV1Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_verdict_api_ocp_verdict_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListVerdictsV1Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_verdict_api_ocp_verdict_api_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListVerdictsV1Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_verdict_api_ocp_verdict_api_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DescribeVerdictV1Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_verdict_api_ocp_verdict_api_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DescribeVerdictV1Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_verdict_api_ocp_verdict_api_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveVerdictV1Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_verdict_api_ocp_verdict_api_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveVerdictV1Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_verdict_api_ocp_verdict_api_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Verdict); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_ocp_verdict_api_ocp_verdict_api_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_ocp_verdict_api_ocp_verdict_api_proto_goTypes,
		DependencyIndexes: file_api_ocp_verdict_api_ocp_verdict_api_proto_depIdxs,
		EnumInfos:         file_api_ocp_verdict_api_ocp_verdict_api_proto_enumTypes,
		MessageInfos:      file_api_ocp_verdict_api_ocp_verdict_api_proto_msgTypes,
	}.Build()
	File_api_ocp_verdict_api_ocp_verdict_api_proto = out.File
	file_api_ocp_verdict_api_ocp_verdict_api_proto_rawDesc = nil
	file_api_ocp_verdict_api_ocp_verdict_api_proto_goTypes = nil
	file_api_ocp_verdict_api_ocp_verdict_api_proto_depIdxs = nil
}
