// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: api/ocp-solution-api/ocp-solution-api.proto

package ocp_solution_api

import (
	ocp_verdict_api "github.com/ozoncp/ocp-solution-api/pkg/ocp-verdict-api"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateSolutionV1Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SolutionId uint64 `protobuf:"varint,1,opt,name=solutionId,proto3" json:"solutionId,omitempty"`
	IssueId    uint64 `protobuf:"varint,2,opt,name=issueId,proto3" json:"issueId,omitempty"`
}

func (x *CreateSolutionV1Request) Reset() {
	*x = CreateSolutionV1Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_solution_api_ocp_solution_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSolutionV1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSolutionV1Request) ProtoMessage() {}

func (x *CreateSolutionV1Request) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_solution_api_ocp_solution_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSolutionV1Request.ProtoReflect.Descriptor instead.
func (*CreateSolutionV1Request) Descriptor() ([]byte, []int) {
	return file_api_ocp_solution_api_ocp_solution_api_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSolutionV1Request) GetSolutionId() uint64 {
	if x != nil {
		return x.SolutionId
	}
	return 0
}

func (x *CreateSolutionV1Request) GetIssueId() uint64 {
	if x != nil {
		return x.IssueId
	}
	return 0
}

type CreateSolutionV1Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Solution *Solution `protobuf:"bytes,1,opt,name=solution,proto3" json:"solution,omitempty"`
}

func (x *CreateSolutionV1Response) Reset() {
	*x = CreateSolutionV1Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_solution_api_ocp_solution_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSolutionV1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSolutionV1Response) ProtoMessage() {}

func (x *CreateSolutionV1Response) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_solution_api_ocp_solution_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSolutionV1Response.ProtoReflect.Descriptor instead.
func (*CreateSolutionV1Response) Descriptor() ([]byte, []int) {
	return file_api_ocp_solution_api_ocp_solution_api_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSolutionV1Response) GetSolution() *Solution {
	if x != nil {
		return x.Solution
	}
	return nil
}

type ListSolutionsV1Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Limit  uint64 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset uint64 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
}

func (x *ListSolutionsV1Request) Reset() {
	*x = ListSolutionsV1Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_solution_api_ocp_solution_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListSolutionsV1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSolutionsV1Request) ProtoMessage() {}

func (x *ListSolutionsV1Request) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_solution_api_ocp_solution_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSolutionsV1Request.ProtoReflect.Descriptor instead.
func (*ListSolutionsV1Request) Descriptor() ([]byte, []int) {
	return file_api_ocp_solution_api_ocp_solution_api_proto_rawDescGZIP(), []int{2}
}

func (x *ListSolutionsV1Request) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListSolutionsV1Request) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListSolutionsV1Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Solutions []*Solution `protobuf:"bytes,1,rep,name=solutions,proto3" json:"solutions,omitempty"`
}

func (x *ListSolutionsV1Response) Reset() {
	*x = ListSolutionsV1Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_solution_api_ocp_solution_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListSolutionsV1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSolutionsV1Response) ProtoMessage() {}

func (x *ListSolutionsV1Response) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_solution_api_ocp_solution_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSolutionsV1Response.ProtoReflect.Descriptor instead.
func (*ListSolutionsV1Response) Descriptor() ([]byte, []int) {
	return file_api_ocp_solution_api_ocp_solution_api_proto_rawDescGZIP(), []int{3}
}

func (x *ListSolutionsV1Response) GetSolutions() []*Solution {
	if x != nil {
		return x.Solutions
	}
	return nil
}

type DescribeSolutionV1Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SolutionId uint64 `protobuf:"varint,1,opt,name=solutionId,proto3" json:"solutionId,omitempty"`
}

func (x *DescribeSolutionV1Request) Reset() {
	*x = DescribeSolutionV1Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_solution_api_ocp_solution_api_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DescribeSolutionV1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeSolutionV1Request) ProtoMessage() {}

func (x *DescribeSolutionV1Request) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_solution_api_ocp_solution_api_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeSolutionV1Request.ProtoReflect.Descriptor instead.
func (*DescribeSolutionV1Request) Descriptor() ([]byte, []int) {
	return file_api_ocp_solution_api_ocp_solution_api_proto_rawDescGZIP(), []int{4}
}

func (x *DescribeSolutionV1Request) GetSolutionId() uint64 {
	if x != nil {
		return x.SolutionId
	}
	return 0
}

type DescribeSolutionV1Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Solution *Solution `protobuf:"bytes,1,opt,name=solution,proto3" json:"solution,omitempty"`
}

func (x *DescribeSolutionV1Response) Reset() {
	*x = DescribeSolutionV1Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_solution_api_ocp_solution_api_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DescribeSolutionV1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeSolutionV1Response) ProtoMessage() {}

func (x *DescribeSolutionV1Response) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_solution_api_ocp_solution_api_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeSolutionV1Response.ProtoReflect.Descriptor instead.
func (*DescribeSolutionV1Response) Descriptor() ([]byte, []int) {
	return file_api_ocp_solution_api_ocp_solution_api_proto_rawDescGZIP(), []int{5}
}

func (x *DescribeSolutionV1Response) GetSolution() *Solution {
	if x != nil {
		return x.Solution
	}
	return nil
}

type RemoveSolutionV1Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SolutionId uint64 `protobuf:"varint,1,opt,name=solutionId,proto3" json:"solutionId,omitempty"`
}

func (x *RemoveSolutionV1Request) Reset() {
	*x = RemoveSolutionV1Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_solution_api_ocp_solution_api_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveSolutionV1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveSolutionV1Request) ProtoMessage() {}

func (x *RemoveSolutionV1Request) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_solution_api_ocp_solution_api_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveSolutionV1Request.ProtoReflect.Descriptor instead.
func (*RemoveSolutionV1Request) Descriptor() ([]byte, []int) {
	return file_api_ocp_solution_api_ocp_solution_api_proto_rawDescGZIP(), []int{6}
}

func (x *RemoveSolutionV1Request) GetSolutionId() uint64 {
	if x != nil {
		return x.SolutionId
	}
	return 0
}

type RemoveSolutionV1Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Found bool `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
}

func (x *RemoveSolutionV1Response) Reset() {
	*x = RemoveSolutionV1Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_solution_api_ocp_solution_api_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveSolutionV1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveSolutionV1Response) ProtoMessage() {}

func (x *RemoveSolutionV1Response) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_solution_api_ocp_solution_api_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveSolutionV1Response.ProtoReflect.Descriptor instead.
func (*RemoveSolutionV1Response) Descriptor() ([]byte, []int) {
	return file_api_ocp_solution_api_ocp_solution_api_proto_rawDescGZIP(), []int{7}
}

func (x *RemoveSolutionV1Response) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type Solution struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SolutionId uint64                   `protobuf:"varint,1,opt,name=solutionId,proto3" json:"solutionId,omitempty"`
	IssueId    uint64                   `protobuf:"varint,2,opt,name=issueId,proto3" json:"issueId,omitempty"`
	Verdict    *ocp_verdict_api.Verdict `protobuf:"bytes,3,opt,name=verdict,proto3" json:"verdict,omitempty"`
}

func (x *Solution) Reset() {
	*x = Solution{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_solution_api_ocp_solution_api_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Solution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Solution) ProtoMessage() {}

func (x *Solution) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_solution_api_ocp_solution_api_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Solution.ProtoReflect.Descriptor instead.
func (*Solution) Descriptor() ([]byte, []int) {
	return file_api_ocp_solution_api_ocp_solution_api_proto_rawDescGZIP(), []int{8}
}

func (x *Solution) GetSolutionId() uint64 {
	if x != nil {
		return x.SolutionId
	}
	return 0
}

func (x *Solution) GetIssueId() uint64 {
	if x != nil {
		return x.IssueId
	}
	return 0
}

func (x *Solution) GetVerdict() *ocp_verdict_api.Verdict {
	if x != nil {
		return x.Verdict
	}
	return nil
}

var File_api_ocp_solution_api_ocp_solution_api_proto protoreflect.FileDescriptor

var file_api_ocp_solution_api_ocp_solution_api_proto_rawDesc = []byte{
	0x0a, 0x2b, 0x61, 0x70, 0x69, 0x2f, 0x6f, 0x63, 0x70, 0x2d, 0x73, 0x6f, 0x6c, 0x75, 0x74, 0x69,
	0x6f, 0x6e, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x6f, 0x63, 0x70, 0x2d, 0x73, 0x6f, 0x6c, 0x75, 0x74,
	0x69, 0x6f, 0x6e, 0x2d, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x6f,
	0x63, 0x70, 0x2e, 0x73, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x61, 0x70, 0x69, 0x1a,
	0x29, 0x61, 0x70, 0x69, 0x2f, 0x6f, 0x63, 0x70, 0x2d, 0x76, 0x65, 0x72, 0x64, 0x69, 0x63, 0x74,
	0x2d, 0x61, 0x70, 0x69, 0x2f, 0x6f, 0x63, 0x70, 0x2d, 0x76, 0x65, 0x72, 0x64, 0x69, 0x63, 0x74,
	0x2d, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x53, 0x0a, 0x17, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x53, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x56, 0x31, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f,
	0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x73, 0x6f, 0x6c, 0x75, 0x74,
	0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x73, 0x73, 0x75, 0x65, 0x49, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x69, 0x73, 0x73, 0x75, 0x65, 0x49, 0x64, 0x22,
	0x52, 0x0a, 0x18, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f,
	0x6e, 0x56, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a, 0x08, 0x73,
	0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x6f, 0x63, 0x70, 0x2e, 0x73, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x53, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x73, 0x6f, 0x6c, 0x75, 0x74,
	0x69, 0x6f, 0x6e, 0x22, 0x46, 0x0a, 0x16, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x6f, 0x6c, 0x75, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x56, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a,
	0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x6c, 0x69,
	0x6d, 0x69, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x22, 0x53, 0x0a, 0x17, 0x4c,
	0x69, 0x73, 0x74, 0x53, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x56, 0x31, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x09, 0x73, 0x6f, 0x6c, 0x75, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x6f, 0x63, 0x70, 0x2e,
	0x73, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x6f, 0x6c,
	0x75, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x09, 0x73, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x22, 0x3b, 0x0a, 0x19, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x53, 0x6f, 0x6c, 0x75,
	0x74, 0x69, 0x6f, 0x6e, 0x56, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a,
	0x0a, 0x73, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x0a, 0x73, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0x54, 0x0a,
	0x1a, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x53, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f,
	0x6e, 0x56, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a, 0x08, 0x73,
	0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x6f, 0x63, 0x70, 0x2e, 0x73, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x53, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x73, 0x6f, 0x6c, 0x75, 0x74,
	0x69, 0x6f, 0x6e, 0x22, 0x39, 0x0a, 0x17, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x53, 0x6f, 0x6c,
	0x75, 0x74, 0x69, 0x6f, 0x6e, 0x56, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e,
	0x0a, 0x0a, 0x73, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x0a, 0x73, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0x30,
	0x0a, 0x18, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x53, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e,
	0x56, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x6f,
	0x75, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x66, 0x6f, 0x75, 0x6e, 0x64,
	0x22, 0x78, 0x0a, 0x08, 0x53, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1e, 0x0a, 0x0a,
	0x73, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x0a, 0x73, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07,
	0x69, 0x73, 0x73, 0x75, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x69,
	0x73, 0x73, 0x75, 0x65, 0x49, 0x64, 0x12, 0x32, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x64, 0x69, 0x63,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6f, 0x63, 0x70, 0x2e, 0x76, 0x65,
	0x72, 0x64, 0x69, 0x63, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x56, 0x65, 0x72, 0x64, 0x69, 0x63,
	0x74, 0x52, 0x07, 0x76, 0x65, 0x72, 0x64, 0x69, 0x63, 0x74, 0x32, 0xc7, 0x03, 0x0a, 0x0e, 0x4f,
	0x63, 0x70, 0x53, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x70, 0x69, 0x12, 0x6b, 0x0a,
	0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x56,
	0x31, 0x12, 0x29, 0x2e, 0x6f, 0x63, 0x70, 0x2e, 0x73, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x6f, 0x6c, 0x75, 0x74,
	0x69, 0x6f, 0x6e, 0x56, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2a, 0x2e, 0x6f,
	0x63, 0x70, 0x2e, 0x73, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x56, 0x31,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x68, 0x0a, 0x0f, 0x4c, 0x69,
	0x73, 0x74, 0x53, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x56, 0x31, 0x12, 0x28, 0x2e,
	0x6f, 0x63, 0x70, 0x2e, 0x73, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x56, 0x31,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x29, 0x2e, 0x6f, 0x63, 0x70, 0x2e, 0x73, 0x6f,
	0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x53,
	0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x56, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x71, 0x0a, 0x12, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65,
	0x53, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x56, 0x31, 0x12, 0x2b, 0x2e, 0x6f, 0x63, 0x70,
	0x2e, 0x73, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x53, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x56, 0x31,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2c, 0x2e, 0x6f, 0x63, 0x70, 0x2e, 0x73, 0x6f,
	0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x62, 0x65, 0x53, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x56, 0x31, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x6b, 0x0a, 0x10, 0x52, 0x65, 0x6d, 0x6f, 0x76,
	0x65, 0x53, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x56, 0x31, 0x12, 0x29, 0x2e, 0x6f, 0x63,
	0x70, 0x2e, 0x73, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x52,
	0x65, 0x6d, 0x6f, 0x76, 0x65, 0x53, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x56, 0x31, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2a, 0x2e, 0x6f, 0x63, 0x70, 0x2e, 0x73, 0x6f, 0x6c,
	0x75, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65,
	0x53, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x56, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x42, 0x4a, 0x5a, 0x48, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x6f, 0x7a, 0x6f, 0x6e, 0x63, 0x70, 0x2f, 0x6f, 0x63, 0x70, 0x2d, 0x73, 0x6f,
	0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x6f,
	0x63, 0x70, 0x2d, 0x73, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x2d, 0x61, 0x70, 0x69, 0x3b,
	0x6f, 0x63, 0x70, 0x5f, 0x73, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x61, 0x70, 0x69,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_ocp_solution_api_ocp_solution_api_proto_rawDescOnce sync.Once
	file_api_ocp_solution_api_ocp_solution_api_proto_rawDescData = file_api_ocp_solution_api_ocp_solution_api_proto_rawDesc
)

func file_api_ocp_solution_api_ocp_solution_api_proto_rawDescGZIP() []byte {
	file_api_ocp_solution_api_ocp_solution_api_proto_rawDescOnce.Do(func() {
		file_api_ocp_solution_api_ocp_solution_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_ocp_solution_api_ocp_solution_api_proto_rawDescData)
	})
	return file_api_ocp_solution_api_ocp_solution_api_proto_rawDescData
}

var file_api_ocp_solution_api_ocp_solution_api_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_api_ocp_solution_api_ocp_solution_api_proto_goTypes = []interface{}{
	(*CreateSolutionV1Request)(nil),    // 0: ocp.solution.api.CreateSolutionV1Request
	(*CreateSolutionV1Response)(nil),   // 1: ocp.solution.api.CreateSolutionV1Response
	(*ListSolutionsV1Request)(nil),     // 2: ocp.solution.api.ListSolutionsV1Request
	(*ListSolutionsV1Response)(nil),    // 3: ocp.solution.api.ListSolutionsV1Response
	(*DescribeSolutionV1Request)(nil),  // 4: ocp.solution.api.DescribeSolutionV1Request
	(*DescribeSolutionV1Response)(nil), // 5: ocp.solution.api.DescribeSolutionV1Response
	(*RemoveSolutionV1Request)(nil),    // 6: ocp.solution.api.RemoveSolutionV1Request
	(*RemoveSolutionV1Response)(nil),   // 7: ocp.solution.api.RemoveSolutionV1Response
	(*Solution)(nil),                   // 8: ocp.solution.api.Solution
	(*ocp_verdict_api.Verdict)(nil),    // 9: ocp.verdict.api.Verdict
}
var file_api_ocp_solution_api_ocp_solution_api_proto_depIdxs = []int32{
	8, // 0: ocp.solution.api.CreateSolutionV1Response.solution:type_name -> ocp.solution.api.Solution
	8, // 1: ocp.solution.api.ListSolutionsV1Response.solutions:type_name -> ocp.solution.api.Solution
	8, // 2: ocp.solution.api.DescribeSolutionV1Response.solution:type_name -> ocp.solution.api.Solution
	9, // 3: ocp.solution.api.Solution.verdict:type_name -> ocp.verdict.api.Verdict
	0, // 4: ocp.solution.api.OcpSolutionApi.CreateSolutionV1:input_type -> ocp.solution.api.CreateSolutionV1Request
	2, // 5: ocp.solution.api.OcpSolutionApi.ListSolutionsV1:input_type -> ocp.solution.api.ListSolutionsV1Request
	4, // 6: ocp.solution.api.OcpSolutionApi.DescribeSolutionV1:input_type -> ocp.solution.api.DescribeSolutionV1Request
	6, // 7: ocp.solution.api.OcpSolutionApi.RemoveSolutionV1:input_type -> ocp.solution.api.RemoveSolutionV1Request
	1, // 8: ocp.solution.api.OcpSolutionApi.CreateSolutionV1:output_type -> ocp.solution.api.CreateSolutionV1Response
	3, // 9: ocp.solution.api.OcpSolutionApi.ListSolutionsV1:output_type -> ocp.solution.api.ListSolutionsV1Response
	5, // 10: ocp.solution.api.OcpSolutionApi.DescribeSolutionV1:output_type -> ocp.solution.api.DescribeSolutionV1Response
	7, // 11: ocp.solution.api.OcpSolutionApi.RemoveSolutionV1:output_type -> ocp.solution.api.RemoveSolutionV1Response
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_ocp_solution_api_ocp_solution_api_proto_init() }
func file_api_ocp_solution_api_ocp_solution_api_proto_init() {
	if File_api_ocp_solution_api_ocp_solution_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_ocp_solution_api_ocp_solution_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSolutionV1Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_solution_api_ocp_solution_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSolutionV1Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_solution_api_ocp_solution_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListSolutionsV1Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_solution_api_ocp_solution_api_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListSolutionsV1Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_solution_api_ocp_solution_api_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DescribeSolutionV1Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_solution_api_ocp_solution_api_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DescribeSolutionV1Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_solution_api_ocp_solution_api_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveSolutionV1Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_solution_api_ocp_solution_api_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveSolutionV1Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_solution_api_ocp_solution_api_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Solution); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_ocp_solution_api_ocp_solution_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_ocp_solution_api_ocp_solution_api_proto_goTypes,
		DependencyIndexes: file_api_ocp_solution_api_ocp_solution_api_proto_depIdxs,
		MessageInfos:      file_api_ocp_solution_api_ocp_solution_api_proto_msgTypes,
	}.Build()
	File_api_ocp_solution_api_ocp_solution_api_proto = out.File
	file_api_ocp_solution_api_ocp_solution_api_proto_rawDesc = nil
	file_api_ocp_solution_api_ocp_solution_api_proto_goTypes = nil
	file_api_ocp_solution_api_ocp_solution_api_proto_depIdxs = nil
}
